version: '3'

services:
  my_db:
    image: postgres:latest
    ports:
      - 9999:5432
    volumes:
      - ./docker-db_data:/var/lib/postgresql
    env_file: .env

  my_server:
    build: .
    # dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./app/:/root/
    entrypoint:
      - tail
      - -f
    depends_on:
      - my_db
    # command: >
    #   "python app.py"
