version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ./docker-db_data:/var/lib/postgresql
    env_file: .env

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      ports:
        - 5000:5000
      volumes:
        - ./app/:/root/
      entrypoint:
        - tail
        - -f
        - /dev/null
      depends_on:
        - db
    # dockerfile: ./Dockerfile
