version: '3'

services:
  my_db:
    image: postgres:latest
    ports:
      - 9999:5432
    volumes:
      - ./docker-db_data:/var/lib/postgresql
    env_file: .env

  my_server:
    build: .
    # dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 8000:8000
    volumes:
      - ./app/:/root/
    entrypoint:
      - bash
      - -c
    depends_on:
      - my_db
    command: >
      "cd /root/tools &&
      cd /root &&
      unlink /etc/nginx/sites-enabled/default &&
      nginx -t &&
      service nginx reload &&
      gunicorn -b 0.0.0.0:8000 app:app"
